name: SatellitesApp

options:
  bundleIdPrefix: com.satellites
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
    tvOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  defaultConfig: Debug
  transitivelyLinkDependencies: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
    SWIFT_TREAT_WARNINGS_AS_ERRORS: true
    DEAD_CODE_STRIPPING: true
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule

configs:
  Debug: debug
  Release: release

packages:
  SatelliteKit:
    url: https://github.com/gavineadie/SatelliteKit.git
    from: 2.0.0

targets:
  SatellitesApp:
    type: application
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - path: Sources/SatellitesApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.satellites.app
        PRODUCT_NAME: SatellitesApp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Satellites
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "-"
    dependencies:
      - target: SatellitesKit

  SatellitesKit:
    type: framework
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - path: Sources/SatellitesKit
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.satellites.kit
        PRODUCT_NAME: SatellitesKit
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        DEFINES_MODULE: true
    dependencies:
      - package: SatelliteKit

  SatellitesAppTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - path: Tests/SatellitesAppTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.satellites.app.tests
        GENERATE_INFOPLIST_FILE: true

  SatellitesKitTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - path: Tests/SatellitesKitTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.satellites.kit.tests
        GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: SatellitesKit

schemes:
  SatellitesApp:
    build:
      targets:
        SatellitesApp: all
        SatellitesKit: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SatellitesApp
        - SatellitesKit
      targets:
        - SatellitesAppTests
        - SatellitesKitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  SatellitesKit:
    build:
      targets:
        SatellitesKit: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SatellitesKit
      targets:
        - SatellitesKitTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
